require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.2

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

OptionalBooleanParameter:
  Enabled: false

RSpec/BlockLength:
  Max: 20

RSpec/DescribeClass:
  Enabled: false

RSpec/NestedGroups:
  Max: 5
